---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: {{ .Values.namespace.label }}
    argocd.argoproj.io/managed-by: openshift-gitops
  name: {{ .Values.namespace.name }}

