apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.permissions.roleName }}
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["privileged"]
    verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.permissions.roleBindingName }}
subjects:
  - kind: ServiceAccount
    name: pipeline
roleRef:
  kind: Role
  name: {{ .Values.permissions.roleName }}
  apiGroup: rbac.authorization.k8s.io

