apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hqoas-spring-maven-pipeline-run-
  namespace: tekton-tasks
spec:
  pipelineRef:
    name: hqoas-spring-maven-pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: maven-repo
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
  - name: git-revision
    value: add-helm