bases:
  - ./common
namespace: hqoas-jdbc-demo
namePrefix: hqoas-spring-
nameSuffix: "-v1"
commonLabels:
  app: hqoas-jdbc-demo
  version: v1
commonAnnotations:
  deployedBy: "argocd"
  chain: "tekton-pipeline"
  environment: "hqoas-spring"
patchesStrategicMerge:
- mem-sizing.yaml
images:
- name: hqoas-jdbc-demo
  newName: default-route-openshift-image-registry.apps.cluster-vxdqr.vxdqr.sandbox1122.opentlc.com/hqoas-jdbc-demo/hqoas-jdbc-demo
  newTag: latest
