apiVersion: v1
kind: Secret
metadata:
  name: quay-credentials
data:
  config.json: ewoJImF1dGhzIjogewoJCSJxdWF5LmlvIjogewoJCQkiYXV0aCI6ICJiV0Y0YVcxcGJHbGhibUlyWW1GamEzTjBZV2RsT2pkRFNWRktNekpYUVVOUFRUVTFNRTR4VnpZM1REQk5Sa1pHU2pWQlRVb3pXa295VDFSWE1rWlFTVGxRU0U5SlRGaFRNRXhNU2xkSVVrMUpXVVZWVGpZPSIKCQl9LAoJCSJyZWdpc3RyeS5naXRsYWIuY29tIjogewoJCQkiYXV0aCI6ICJiV0Y0YVcxcGJHbGxiaTVpWld4cGJtZGhYMkk2WjJ4d1lYUXRTa2h2TTNOVk9EazJjMEpPZFRSbmNXbHBUbEk9IgoJCX0KCX0KfQ==